import Head from 'next/head'
import { useForm } from 'react-hook-form';
import { Prisma} from '@prisma/client';
//ver video completo https://react-hook-form.com/get-started

const handleCreate = async (data:{})=> {
  console.log('data',data)
  const response = await fetch('/api/user', {
    method: 'POST',
    body: JSON.stringify(data)
  });

  console.log("response",await response.json());
  

  // if (!response.ok) {
  //   throw new Error(response.statusText);
  // }
  // return await response.json();
}

export default function Home( ) {
  const { register, handleSubmit } = useForm();
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        
      </Head>
      <main>
        <p>Create</p>
      {/* {initialContacts.map((c, i: number) => (
            <div className="mb-3" key={i}>
              {c.wordSpanish}
            </div>
          ))} */}

          <form onSubmit={handleSubmit(handleCreate)}>

            <input  {...register("email")} type="email"/>
            <input  {...register("password")} type="password" />
            <button type="submit">assas</button>
          </form>
      </main>
    </>
  )
}


