import Head from 'next/head'

import LoginSignup from '../components/LoginSignup'
import Header from '../components/Header'

import Initialtable from '../components/Initialtable'
import Realtable from '@/components/Realtable';
import { useState,useEffect } from 'react';
import Filter from '@/components/Filter';
//ver video completo https://react-hook-form.com/get-started



export default function Home() {
  const [ view, setView ] = useState("landing")
  const [user, setUser] = useState("")
  useEffect(() => {
    const item = sessionStorage.getItem("userTestEnglish")
    if (item !=null){
      setUser(item)
    }  
  }, [])
  return (
    <>
      <Head>
        <title>testEnglish</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <script src="https://cdn.tailwindcss.com"></script>
      </Head>
      <main>
        <Header view={view} setView={setView} ></Header>
        <Filter/>
        {view=="login"||view=="signup"?<LoginSignup view={view} setView={setView} />:<></>}
        {user.length == 0 ?<Initialtable />:
        <Realtable/>}
      </main>
    </>
  )
}


